Repository joye-seo/Team7ContactApp, pull requests merged in 2023-09, with the labels that each got.

#3 xml 뼈대 완성
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/team7contactapp/home/MyPageFragment.kt
  app/src/main/res/drawable/gradient_overlay.xml
  app/src/main/res/drawable/mypageimage.JPG
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/mypagetextstyle.xml
Labels: UI

#5 [Enhancement / UI] 바텀네비게이션 기능 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/team7contactapp/home/HomeActivity.kt
  app/src/main/res/drawable/ic_contact.png
  app/src/main/res/drawable/ic_contact_click.png
  app/src/main/res/drawable/ic_history.png
  app/src/main/res/drawable/ic_history_click.png
  app/src/main/res/drawable/ic_keypad.png
  app/src/main/res/drawable/ic_keypad_click.png
  app/src/main/res/drawable/ic_mypage.png
  app/src/main/res/drawable/ic_mypage_click.png
  app/src/main/res/drawable/ic_plus.png
  app/src/main/res/drawable/selector_contact.xml
  app/src/main/res/drawable/selector_history.xml
  app/src/main/res/drawable/selector_keypad.xml
  app/src/main/res/drawable/selector_mypage.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/menu/bottom_navigation.xml
Labels: enhancement, UI

#6 build.gradle > implementation 'de.hdodenhof:circleimageview:3.1.0' 추가…
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/res/drawable/donghyun.png
  app/src/main/res/drawable/jinjoo.png
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/item_contact.xml
Labels: UI

#7 contact_detail init commit
  app/src/main/res/layout/activity_contact_detail.xml
Labels: init

#8 contact_detail Image file and ScrollView commit
  app/src/main/res/drawable/profile.png
  app/src/main/res/layout/activity_contact_detail.xml
Labels: modify

#9 [UI][Enhancement]키패드 UI 및 버튼 기능 활성화
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team7contactapp/home/KeypadFragment.kt
  app/src/main/java/com/example/team7contactapp/home/RecordFragment.kt
  app/src/main/res/drawable/ic_add.png
  app/src/main/res/drawable/ic_close.png
  app/src/main/res/drawable/ic_ellipsis.png
  app/src/main/res/drawable/ic_magnifying.png
  app/src/main/res/drawable/ic_plus.png
  app/src/main/res/drawable/ic_rounded.png
  app/src/main/res/drawable/ic_telephone.png
  app/src/main/res/drawable/ic_video_call.png
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/fragment_keypad.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#10 [Enhancement/UI] viewPager2기능구현 완료
  app/src/main/java/com/example/team7contactapp/adapter/HomeViewPagerAdapter.kt
  app/src/main/java/com/example/team7contactapp/home/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
Labels: enhancement, UI

#12 [UI] RecordActivity UI 구현
  app/src/main/java/com/example/team7contactapp/NameAdapter.kt
  app/src/main/java/com/example/team7contactapp/Names.kt
  app/src/main/java/com/example/team7contactapp/home/KeypadFragment.kt
  app/src/main/java/com/example/team7contactapp/home/RecordFragment.kt
  app/src/main/res/drawable/ic_call1.png
  app/src/main/res/drawable/ic_call2.png
  app/src/main/res/drawable/ic_call3.png
  app/src/main/res/drawable/ic_menu.png
  app/src/main/res/layout/adrees_item.xml
  app/src/main/res/layout/fragment_record.xml
Labels: enhancement, UI

#13 colors.xml / gray추가
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/values/colors.xml
Labels: UI

#14 [UI] 연락처 추가 xml 작성
  .idea/misc.xml
  app/src/main/java/com/example/team7contactapp/ContactDialogFragment.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/adapter/HomeViewPagerAdapter.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/java/com/example/team7contactapp/home/HistoryFragment.kt
  app/src/main/java/com/example/team7contactapp/home/HomeActivity.kt
  app/src/main/res/drawable/ic_image_add.png
  app/src/main/res/drawable/shape_edit_text.xml
  app/src/main/res/layout/fragment_contact_dialog.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/values/colors.xml
Labels: UI

#15 Contact fragment
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
Labels: modify

#16 생성자 이름 맞춤
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
Labels: modify

#17 Feature/detail
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: modify

#18 [Chain][Modify] 화면 수정 & 데이터 연결
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/java/com/example/team7contactapp/home/HistoryFragment.kt
  app/src/main/java/com/example/team7contactapp/home/HomeActivity.kt
  app/src/main/java/com/example/team7contactapp/home/KeypadFragment.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_contact_dialog.xml
  app/src/main/res/layout/fragment_keypad.xml
Labels: chain, modify

#19 [UI] Record 항목 클릭시 UI 하나만 켜지도록 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/team7contactapp/NameAdapter.kt
  app/src/main/java/com/example/team7contactapp/Names.kt
  app/src/main/java/com/example/team7contactapp/home/HistoryFragment.kt
  app/src/main/res/layout/adrees_item.xml
Labels: enhancement, UI

#20 Detail Activity 로 데이터 전달
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: chain, modify

#21 [Modify]Detail Activity / back 이미지 추가
  app/src/main/res/drawable/back.png
Labels: modify

#24 [Fix] 데이터클래스 내용 변경
  app/build.gradle
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
Labels: modify

#25 [Feat] Detail page 즐겨찾기 on/off 추가
  .idea/misc.xml
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: enhancement

#26 [Enhancement][Modify][UI] ContactDialogFragment 화면 기능 구현
  app/src/main/java/com/example/team7contactapp/ContactDialogFragment.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/java/com/example/team7contactapp/home/HomeActivity.kt
  app/src/main/java/com/example/team7contactapp/home/MyPageFragment.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_contact_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, UI, modify

#27 [FEAT]Swipe-to-Action 오른쪽 스와이프 실행 시 전화 연결
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
Labels: modify

#29 Stickeyheader
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/res/drawable/jangwonyoung.png
  app/src/main/res/drawable/jpark.png
  app/src/main/res/drawable/jungwoosung.png
  app/src/main/res/drawable/jyp.png
  app/src/main/res/drawable/kangwonki.png
  app/src/main/res/drawable/kimchangsub.png
  app/src/main/res/drawable/kwonsangwoo.png
Labels: UI

#30 Stickeyheader
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/ContactDialogFragment.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
Labels: modify

#32 [UI] Recode 페이지 UI 수정
  app/src/main/java/com/example/team7contactapp/home/HistoryFragment.kt
  app/src/main/res/layout/adrees_item.xml
Labels: UI

#33 Stickeyheader
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/res/drawable/ljm.png
  app/src/main/res/drawable/sungjin.png
Labels: modify

#37 [Enhancement][Modify][UI] 리사이클러뷰 추가 기능 구현
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/ContactDialogFragment.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
  app/src/main/res/drawable/bg_contact_grid.xml
  app/src/main/res/drawable/bg_round_border.xml
  app/src/main/res/drawable/ic_more.png
  app/src/main/res/drawable/ic_search.png
  app/src/main/res/drawable/img_profile_soohyun.jpeg
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_contact_dialog.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/item_contact_view_grid.xml
  app/src/main/res/menu/menu_contact.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, UI, modify

#38 [Modify] 더미데이터 몇개 삭제
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/team7contactapp/data/MyItem.kt
Labels: modify

#40 [Modify]상세 페이지에서 전화 버튼, 수정페이지 추가
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/DetailModityActivity.kt
  app/src/main/java/com/example/team7contactapp/home/HomeActivity.kt
  app/src/main/res/layout/activity_detail_modity.xml
Labels: modify

#44 Feature/contact recycler modify
  app/src/main/java/com/example/team7contactapp/ContactDetailActivity.kt
  app/src/main/java/com/example/team7contactapp/adapter/ContactFragmentAdapter.kt
  app/src/main/java/com/example/team7contactapp/home/ContactFragment.kt
  app/src/main/res/layout/item_contact_view_grid.xml
  app/src/main/res/menu/menu_contact.xml
Labels: enhancement, modify
